In [1]:
import torch

In [2]:
I = torch.tensor([[1,0], [0,1]])
print('I = \n', I)
print('I.ndimension() = ', I.ndimension())
print('I.shape = ', I.shape)

I = 
 tensor([[1, 0],
        [0, 1]])
I.ndimension() =  2
I.shape =  torch.Size([2, 2])


In [ ]:
I1 = torch.eye(2)   # 单位阵
I1

tensor([[1., 0.],
        [0., 1.]])

In [6]:
z = torch.randn((4,4))
print(z)
print(z[1, :])
print(z[1:3, :2])

tensor([[ 1.3184,  0.6487,  0.7557, -0.6787],
        [-0.6118, -0.5305, -0.6568, -0.0726],
        [ 0.3631, -0.7684,  1.5212,  0.5558],
        [ 0.1419,  0.2456, -0.5595,  1.0284]])
tensor([-0.6118, -0.5305, -0.6568, -0.0726])
tensor([[-0.6118, -0.5305],
        [ 0.3631, -0.7684]])


In [7]:
pauli_z = I1.clone()
pauli_z[1,1] =  -1
I1, pauli_z

(tensor([[1., 0.],
         [0., 1.]]),
 tensor([[ 1.,  0.],
         [ 0., -1.]]))

In [8]:
K = I1 * 1
K[1,1] = -1
I1, K

(tensor([[1., 0.],
         [0., 1.]]),
 tensor([[ 1.,  0.],
         [ 0., -1.]]))

In [ ]:
# I1的值改变了，利用等号赋值并没有创建新内存
J = I1
J[1,1] = -1
I1, J

(tensor([[ 1.,  0.],
         [ 0., -1.]]),
 tensor([[ 1.,  0.],
         [ 0., -1.]]))

In [11]:
x = torch.tensor([1,3,5,7])
x1 = torch.reshape(x, [2,2])
x1_ = x.reshape(2,2)
x, x1, x1_

(tensor([1, 3, 5, 7]),
 tensor([[1, 3],
         [5, 7]]),
 tensor([[1, 3],
         [5, 7]]))

In [12]:
x2 = x1.permute(1, 0)
x2_ = x1.t()
x2, x2_

(tensor([[1, 5],
         [3, 7]]),
 tensor([[1, 5],
         [3, 7]]))

In [14]:
T = torch.randn(2,3,4)
print(T.shape)
V = T.flatten()
print(V.shape)
print('flatten与reshape向量化所得结果的差别', (V-T.reshape(-1)).norm().item())
print('矩阵化T[0,1]的形状为', T.reshape(-1,4).shape)

torch.Size([2, 3, 4])
torch.Size([24])
flatten与reshape向量化所得结果的差别 0.0
矩阵化T[0,1]的形状为 torch.Size([6, 4])


In [17]:
u = torch.tensor([1,2,3,4])
v = torch.tensor([2,4,6,8])
c = 2
d = torch.tensor([2])

print('u*c=', u*c)
print('u*d=', u*d)
print('u+c=', u+c)
print('u+v=', u+v)
print('u*v=', u*v)

u*c= tensor([2, 4, 6, 8])
u*d= tensor([2, 4, 6, 8])
u+c= tensor([3, 4, 5, 6])
u+v= tensor([ 3,  6,  9, 12])
u*v= tensor([ 2,  8, 18, 32])


In [18]:
u = torch.tensor([1,2,3,4])
v = torch.tensor([2,4,6,8])
print('向量外积outer= \n', u.outer(v))
print('向量外积einsum= \n', torch.einsum('a,b->ab', u, v))

向量外积outer= 
 tensor([[ 2,  4,  6,  8],
        [ 4,  8, 12, 16],
        [ 6, 12, 18, 24],
        [ 8, 16, 24, 32]])
向量外积einsum= 
 tensor([[ 2,  4,  6,  8],
        [ 4,  8, 12, 16],
        [ 6, 12, 18, 24],
        [ 8, 16, 24, 32]])


In [ ]:
# reshape, view, permute

# reshape 重新调整张量的形状，但可能会复制数据（如果原始数据在内存中不是连续的）。
# 创建一个连续的张量
x = torch.arange(12)
print(x.shape)  # torch.Size([12])

# 使用 reshape 改变形状
y = x.reshape(3, 4)
print(y.shape)  # torch.Size([3, 4])

# 修改 y 的值，x 也会同步变化（说明没有复制数据，原始数据在内存中是连续的）
y[0, 0] = 999
print(x)  # x[0] 变成了 999


torch.Size([12])
torch.Size([3, 4])
tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])


In [20]:
x = torch.arange(12)
y = x.view(3, 4)
print(y.shape)  # torch.Size([3, 4])

# 修改 y 的值，x 也会同步变化（说明没有复制数据）
y[0, 0] = 999
print(x)  # x[0] 变成了 999


torch.Size([3, 4])
tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])


In [22]:
# 如果数据内存不连续，view会报错
x = torch.randn(2, 3, 4)
y = x.permute(1, 0, 2)  # 交换维度
z = y.view(3, 8)  # ❌ 这里会报错 RuntimeError: view size is not compatible with input tensor


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [ ]:
z = y.contiguous().view(3, 8)  # 先变成连续的
z

tensor([[-0.3316,  0.4163,  0.8924, -2.4649, -1.9064,  1.7005, -1.0033, -2.6787],
        [-0.8830,  2.5085, -1.4781,  0.7459, -0.4559,  0.1434,  1.1997, -0.2149],
        [-0.7904, -1.2990,  1.5640,  1.2060, -0.7360, -0.6100, -0.1774,  0.5740]])

In [27]:
x = torch.randn(2, 3, 4)  # (batch, channels, height)
print(x.shape)  # torch.Size([2, 3, 4])
print(x)

y = x.permute(1, 0, 2)  # 交换第 0 维和第 1 维
print(y.shape)  # torch.Size([3, 2, 4])
print(y)

print(y.is_contiguous())  # False
z = y.contiguous().view(3, 8)  # 先变成连续的，再 reshape

torch.Size([2, 3, 4])
tensor([[[-0.7190, -1.8848, -0.1372,  0.8433],
         [ 0.7617,  0.4837,  0.4637, -1.2413],
         [ 2.1244, -0.3036, -0.2629,  0.1694]],

        [[-0.3058,  1.5784,  2.1918, -0.8442],
         [ 1.4226, -0.4437,  1.7754, -0.0585],
         [-0.0236,  0.7223, -0.2508,  0.5784]]])
torch.Size([3, 2, 4])
tensor([[[-0.7190, -1.8848, -0.1372,  0.8433],
         [-0.3058,  1.5784,  2.1918, -0.8442]],

        [[ 0.7617,  0.4837,  0.4637, -1.2413],
         [ 1.4226, -0.4437,  1.7754, -0.0585]],

        [[ 2.1244, -0.3036, -0.2629,  0.1694],
         [-0.0236,  0.7223, -0.2508,  0.5784]]])
False
